BIT_VECTOR_NAME = "Bit Vector"
CLUST_PROP_NAME = "Proportion"
LOG_OBS_NAME = "Log Observed"
LOG_EXP_NAME = "Log Expected"
SEMI_G_ANOMALY = "Anomaly (O×log[O/E])"
JACKPOT_QUOTIENT = "Jackpotting quotient"
