from pathlib import Path
from typing import Iterable

from click import command

from .write import ensembles
from .. import mask as mask_mod, cluster as cluster_mod
from ..core import path
from ..core.arg import (CMD_ENSEMBLES,
                        merge_params,
                        opt_tile_length,
                        opt_tile_min_overlap,
                        opt_erase_tiles,
                        opt_pair_fdr,
                        opt_min_pairs,
                        opt_threshold_multiplier,
                        opt_min_cluster_length,
                        opt_max_cluster_length,
                        opt_gap_mode)
from ..core.run import run_func
from ..core.seq import (DNA)
from ..core.task import as_list_of_tuples, dispatch
from ..relate.dataset import load_relate_dataset


@run_func(CMD_ENSEMBLES)
def run(input_path: Iterable[str | Path], *,
        # General options
        branch: str,
        tmp_pfx: str | Path,
        keep_tmp: bool,
        brotli_level: int,
        force: bool,
        num_cpus: int,
        # Ensembles options
        tile_length: int,
        tile_min_overlap: float,
        erase_tiles: bool,
        pair_fdr: float,
        min_pairs: int,
        threshold_multiplier: float,
        min_cluster_length: int,
        max_cluster_length: int,
        gap_mode: str,
        # Mask options
        mask_coords: Iterable[tuple[str, int, int]],
        mask_primers: Iterable[tuple[str, DNA, DNA]],
        primer_gap: int,
        mask_regions_file: str | None,
        count_del: bool,
        count_ins: bool,
        no_mut: Iterable[str],
        only_mut: Iterable[str],
        probe: str,
        mask_a: bool | None,
        mask_c: bool | None,
        mask_g: bool | None,
        mask_u: bool | None,
        mask_polya: int,
        mask_pos: Iterable[tuple[str, int]],
        mask_pos_file: Iterable[str | Path],
        mask_read: Iterable[str],
        mask_read_file: Iterable[str | Path],
        mask_discontig: bool,
        min_ncov_read: int,
        min_finfo_read: float,
        max_fmut_read: float,
        min_mut_gap: int | None,
        mut_collisions: str,
        min_ninfo_pos: int,
        max_fmut_pos: float,
        quick_unbias: bool,
        quick_unbias_thresh: float,
        max_mask_iter: int,
        mask_pos_table: bool,
        mask_read_table: bool,
        # Cluster options
        min_clusters: int,
        max_clusters: int,
        min_em_runs: int,
        max_em_runs: int,
        jackpot: bool,
        jackpot_conf_level: float,
        max_jackpot_quotient: float,
        max_jackpot_sims: int,
        jackpot_max_data: int,
        min_em_iter: int,
        max_em_iter: int,
        em_thresh: float,
        min_marcd_run: float,
        max_pearson_run: float,
        max_arcd_vs_ens_avg: float,
        max_gini_run: float,
        max_loglike_vs_best: float,
        min_pearson_vs_best: float,
        max_marcd_vs_best: float,
        try_all_ks: bool,
        write_all_ks: bool,
        cluster_pos_table: bool,
        cluster_abundance_table: bool,
        verify_times: bool,
        seed: int | None):
    """ Infer independent structure ensembles along an entire RNA. """
    seg_types = load_relate_dataset.report_path_seg_types
    relate_report_files = list(path.find_files_chain(input_path, seg_types))
    kwargs = dict(branch=branch,
                  tmp_pfx=tmp_pfx,
                  keep_tmp=keep_tmp,
                  brotli_level=brotli_level,
                  force=force,
                  num_cpus=num_cpus,
                  # Ensembles options
                  tile_length=tile_length,
                  tile_min_overlap=tile_min_overlap,
                  erase_tiles=erase_tiles,
                  pair_fdr=pair_fdr,
                  min_pairs=min_pairs,
                  threshold_multiplier=threshold_multiplier,
                  min_cluster_length=min_cluster_length,
                  max_cluster_length=max_cluster_length,
                  gap_mode=gap_mode,
                  # Mask options
                  mask_coords=mask_coords,
                  mask_primers=mask_primers,
                  primer_gap=primer_gap,
                  mask_regions_file=mask_regions_file,
                  count_del=count_del,
                  count_ins=count_ins,
                  no_mut=no_mut,
                  only_mut=only_mut,
                  probe=probe,
                  mask_a=mask_a,
                  mask_c=mask_c,
                  mask_g=mask_g,
                  mask_u=mask_u,
                  mask_polya=mask_polya,
                  mask_pos=mask_pos,
                  mask_pos_file=mask_pos_file,
                  mask_read=mask_read,
                  mask_read_file=mask_read_file,
                  mask_discontig=mask_discontig,
                  min_ncov_read=min_ncov_read,
                  min_finfo_read=min_finfo_read,
                  max_fmut_read=max_fmut_read,
                  min_mut_gap=min_mut_gap,
                  mut_collisions=mut_collisions,
                  min_ninfo_pos=min_ninfo_pos,
                  max_fmut_pos=max_fmut_pos,
                  quick_unbias=quick_unbias,
                  quick_unbias_thresh=quick_unbias_thresh,
                  max_mask_iter=max_mask_iter,
                  mask_pos_table=mask_pos_table,
                  mask_read_table=mask_read_table,
                  # Cluster options
                  min_clusters=min_clusters,
                  max_clusters=max_clusters,
                  min_em_runs=min_em_runs,
                  max_em_runs=max_em_runs,
                  jackpot=jackpot,
                  jackpot_conf_level=jackpot_conf_level,
                  max_jackpot_quotient=max_jackpot_quotient,
                  max_jackpot_sims=max_jackpot_sims,
                  jackpot_max_data=jackpot_max_data,
                  min_em_iter=min_em_iter,
                  max_em_iter=max_em_iter,
                  em_thresh=em_thresh,
                  min_marcd_run=min_marcd_run,
                  max_pearson_run=max_pearson_run,
                  max_arcd_vs_ens_avg=max_arcd_vs_ens_avg,
                  max_gini_run=max_gini_run,
                  max_loglike_vs_best=max_loglike_vs_best,
                  min_pearson_vs_best=min_pearson_vs_best,
                  max_marcd_vs_best=max_marcd_vs_best,
                  try_all_ks=try_all_ks,
                  write_all_ks=write_all_ks,
                  cluster_pos_table=cluster_pos_table,
                  cluster_abundance_table=cluster_abundance_table,
                  verify_times=verify_times,
                  seed=seed)
    return dispatch(ensembles,
                    num_cpus=num_cpus,
                    pass_num_cpus=True,
                    as_list=True,
                    ordered=False,
                    raise_on_error=False,
                    args=as_list_of_tuples(relate_report_files),
                    kwargs=kwargs)


params = merge_params(mask_mod.params,
                      cluster_mod.params,
                      [opt_tile_length,
                       opt_tile_min_overlap,
                       opt_erase_tiles,
                       opt_pair_fdr,
                       opt_min_pairs,
                       opt_threshold_multiplier,
                       opt_min_cluster_length,
                       opt_max_cluster_length,
                       opt_gap_mode])


@command(CMD_ENSEMBLES, params=params)
def cli(*args, **kwargs):
    """ Infer independent structure ensembles along an entire RNA. """
    return run(*args, **kwargs)
